server:
  port: 8888
spring:
  application:
    name: iot-platform-zuul
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/smart_warehouse
    username: postgres
    password: 123456
zuul:
  prefix: /api
  routes:
    platformLocation:
      path: /platformLocation/**
      service-id: iot-platform-location-server
    oauth2:
      path: /oauth2/**
      service-id: iot-platform-oauth2
